---
  # geerlingguy.docker doesn't update cache before installing packages
  # Results in gnupg2 not being found
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false

- name: Install docker-compose
  pip:
    name: docker-compose
