---
- include_tasks: timesyncd.yml

- include_tasks: docker.yml
  when: installation_mode == "docker"

- include_tasks: rocket_pool.yml

- include_tasks: monitoring.yml
  when: monitoring|bool == true
