---
- name: Create ~/bin directory
  file:
    state: directory
    path: ~/bin

- name: Download Rocket Pool binary
  get_url:
    url: https://github.com/rocket-pool/smartnode-install/releases/{{ rocket_pool_version }}/download/rocketpool-cli-linux-amd64
    dest: ~/bin/rocketpool
    mode: u=rwx,g=rx,o=rx

- name: Create ~/.rocketpool directory
  file:
    state: directory
    path: ~/.rocketpool

- name: Download Rocket Pool configuration
  unarchive:
    src: https://github.com/rocket-pool/smartnode-install/releases/{{ rocket_pool_version }}/download/rp-smartnode-install.tar.xz
    dest: ~/.rocketpool
    remote_src: yes
    # Unpack only the necessary files
    extra_opts: [--strip-components=3]
  args:
    creates: ~/.rocketpool/chains

- name: Create settings file
  template:
    src: settings.yml.j2
    dest: ~/.rocketpool/settings.yml

- include_tasks: geth_configuration.yml
  when: eth1_client == "geth"

- include_tasks: lighthouse_configuration.yml
  when: eth2_client == "lighthouse"

- include_tasks: prysm_configuration.yml
  when: eth2_client == "prysm"

- name: Start Rocket Pool services
  shell:
    cmd: ~/bin/rocketpool {{ '--allow-root' if (hostvars[inventory_hostname].molecule_file is defined) else '' }} service start
  args:
    creates: ~/.rocketpool/data
  when: start_containers|bool == true
